### ISSUE TITLE
[Suggestion] - Create CoreModel for common fields

### ISSUE THREAD

**Issue by iamnotagentleman** [tugcanolgun/vigilio#3]
Hi, for your common fields in model, you can create abstract model for don't repeat  fields in all models.

Ex:
```
class CoreModel(models.Model):
   created_at = models.DateTimeField()
   class Meta:
      abstract  = True
```
further reading: https://docs.djangoproject.com/en/3.1/topics/db/models/#abstract-base-classes

**Comment by tugcanolgun** [comment]
That's a very good suggestion. Thank you.
